version: '3.5'

services:
  pixplot:
    container_name: pixplot
    build:
      context: ./docker
      network: host
    ports:
        - "5000:5000"
    volumes:
      - /home/michael/Desktop/oeff/:/home
      #- /home/michael/Desktop/oeff/oeff_resized/:/home/images
      - /home/michael/Desktop/images/:/home/images
    working_dir: /home

