version: '3.5'

services:
  pixplot:
    container_name: pixplot
    build:
      context: ./docker
      network: host
    ports:
        - "5000:5000"
    volumes:
      - /home/michael/Documents/pix-plot/pixplot/:/home
      - /home/michael/Desktop/test_oeff/:/home/images
      #- /home/michael/Desktop/test_oeff/:/home/images
    working_dir: /home

